FROM python:3.9-slim

# تثبيت المكتبات اللازمة للنظام (لعمل matplotlib و pandas)
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# نسخ ملف المتطلبات وتثبيته
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# نسخ الكود البرمجي
COPY . .

# أمر التشغيل الأساسي
CMD ["python", "main.py"]
